### ISSUE TITLE
--no-proxy not working

### ISSUE THREAD

**Issue by revunix** [AlyoshaVasilieva/luminous-ttv#11]
Hello, I have a VPS in Russia and would like to make my own proxy. However, `--no-proxy` does not work. What can I do there?
It only works with Hola. I also have a socks5 on this server, but he would rather not connect with that either.

![CleanShot 2023-05-29 at 23 33 17](https://github.com/AlyoshaVasilieva/luminous-ttv/assets/4172418/13070b70-a8c5-40d6-86f3-2e70a0bcd340)

**Comment by AlyoshaVasilieva** [comment]
In no-proxy mode I don't think it has any output at startup. Can it not be connected to?

But looking at it I think I did find a bug, so I'll do some tests in a bit.

**Comment by revunix** [comment]
No, the server does not start at all. Therefore it is not possible to connect to it. It would be great if you could fix the error. I also tried it with another server. Unfortunately the same problem.

**Comment by AlyoshaVasilieva** [comment]
I can't reproduce with [v0.5.3](https://github.com/AlyoshaVasilieva/luminous-ttv/releases/tag/v0.5.3). Testing on my VPS confirmed it works.
