### ISSUE TITLE
Question about the Bulgaria proxy

### ISSUE THREAD

**Issue by thinkpad4** [AlyoshaVasilieva/luminous-ttv#14]
Does that proxy work?  It's shown on the status page but `bg.luminous.dev` doesn't work

**Comment by AlyoshaVasilieva** [comment]
It's running a pre-0.5 version so it doesn't support TTV-LOL. It's a very low-end server (256MB RAM, kernel 2.6, OS EOL'd and can't be updated) that expires in a couple of weeks, so you aren't missing out.
