### ISSUE TITLE
Partially fixing m3u8 proxying method

### ISSUE THREAD

**Issue by zGato** [AlyoshaVasilieva/luminous-ttv#16]
Hey, I have some information regarding a possibility to fix for all EU/UK users this method of proxying.

I can't find any contact info of you, so if you're willing to hear my thoughts, please DM me on Discord: `zgato_`

Either way, this may be only a partial patch, and 100% only for EU/UK users, so it may not be worth it to implement. 

Thank you for your great project either way.

**Comment by AlyoshaVasilieva** [comment]
I have attempted to friend you on Discord, which I think is how to DM you. (I don't use it often.)

Well, I'm lazy, at some point I should VPN into EU and test to see what's going wrong...
