### ISSUE TITLE
Which license: GPL-3.0-only or GPL-3.0-or-later?

### ISSUE THREAD

**Issue by alexanderjkslfj** [AlyoshaVasilieva/luminous-ttv#21]
I was looking into packaging this project and wondered which SPDX identifier I should use: `GPL-3.0-only` or `GPL-3.0-or-later`?

**Comment by AlyoshaVasilieva** [comment]
`-only`:

https://github.com/AlyoshaVasilieva/luminous-ttv/blob/2c0a52613067b6f0222c7b145e8b8d2af8034691/Cargo.toml#L7
