### ISSUE TITLE
Feature Request; Similar TTV LOL requests.

### ISSUE THREAD

**Issue by Sokoloft** [AlyoshaVasilieva/luminous-ttv#5]
Hello,

Twire has an option to add a proxy URL in its settings shown [here](https://github.com/twireapp/Twire/pull/217). However it only seems to work with api.ttv.lol URL.
I'm wondering if its possible to make this project handle requests similarly to ttv lol. 
I've found this project works every time. Whereas ttv lol works 50% of the time. 
I'd love to host this on a rpi zero on my network. Having my tablet, laptop and desktop pointing to them.

There is an edited twitch.py someone made [here ](https://www.reddit.com/r/Streamlink/comments/yr29jz/comment/ixeuzeq/)so it'd even work with streamlink for my laptop/desktop.

I tried changing the URL in the twitch.py file from https://api.ttv.lol to http://localhost:9595 and I received no confirmation in the luminous-ttv prompt. 

Thanks.

**Comment by AlyoshaVasilieva** [comment]
Can you try version 0.5.0? I've attempted to add support for TTV-LOL's API.

**Comment by Sokoloft** [comment]
I am right now though I'm currently testing. So far it works with streamlink using the twitch.py file I linked in my original post. streamlink-twitch-gui had an error a couple times but I can't get it to reproduce it. However it won't work with twire as of yet. It could be something to do with me hosting luminous on a windows pc. Maybe something with the firewall is preventing my phone from connecting to it.

**Comment by AlyoshaVasilieva** [comment]
You'll need to run luminous-ttv with `--address 0.0.0.0` as it only listens on localhost by default, which won't allow external connections. Also point Twire to whatever your computer's IP address is. Also, yes, maybe firewall issue.

Alternatively, try pointing your phone at `https://eu2.luminous.dev` to test Twire. I'll see if I can remember how to build Android apps to test it myself

**Comment by Sokoloft** [comment]
It doesn't seem like its working unfortunately. At least for twire. I added the address parameter and I still don't see any indication that my phone is getting connection to luminous. I tried the .dev domain and I'm unsure as to if it worked either. I was still seeing the pre-roll purple screen on some streams. I have it with a stream up set to your .dev domain, waiting to see if I get an ad or not.

**Comment by Sokoloft** [comment]
As well as just so you know. On that reddit post I asked the person if they could make it compatible with the prior release of luminous. They did and [this ](https://pastebin.com/1pZxxC2W)is the twitch.py. However now their original ttv.lol twitch.py file works with luminous as long as you change the address in the twitch.py.

**Comment by AlyoshaVasilieva** [comment]
The Twire PR with M3U proxy support doesn't work for me at all (can't load anything) so I unfortunately can't debug whatever's going wrong with it.

**Comment by Sokoloft** [comment]
I'm sorry. So I was using the release version of twire from f-droid. Which does not support video proxy. The setting I was setting was image proxy, whatever that is. 

I built the ttv.lol branch found [here ](https://github.com/Nickwasused/Twire/tree/try-ttv.lol)and I seem to have the same issue you have. Gives some oops twitch's servers can't be found. This branch could be using twitchs old helix? Api that was discontinued earlier in the year iirc. That could be the issue.

**Comment by Sokoloft** [comment]
Well I'll close this issue. Thanks for making it work similarly to how ttv lol requests work. Sorry about the confusion with Twire. Just waiting to hear back to see if that twire fork gets fixed. I might look into it myself and fork twire, but its sort of beyond me.
