### ISSUE TITLE
proxys with user:pass 

### ISSUE THREAD

**Issue by revunix** [AlyoshaVasilieva/luminous-ttv#6]
I have tried to connect with a https proxy from proxy6.net, but it wouldn't let me connect to a proxy with user:pass@ip 
Is there a workaround, or just didn't work with this script?

![SCR-20221204-xk-2](https://user-images.githubusercontent.com/4172418/205466887-b1ca9f7f-7386-49da-a74f-46eeb32601fb.png)

**Comment by AlyoshaVasilieva** [comment]
I did some quick tests and authing to an HTTPS proxy works fine for me. If you use your proxy in a browser can it load Twitch?

**Comment by revunix** [comment]
Nope. It's also not working. Can you recommend a cheap proxy service?

**Comment by AlyoshaVasilieva** [comment]
I use servers running VPNs in containers instead of proxies. You can set the extension to use one of my servers to save effort, like `https://eu.luminous.dev`
