### ISSUE TITLE
Does Luminous support ttvlol protocol?

### ISSUE THREAD

**Issue by thinkpad4** [AlyoshaVasilieva/luminous-ttv#8]
Hi, what I mean is if I use eu.luminous.dev and I add it to a extension that supports ttvlol's API routes (/playlist and /vod) would it work?

Thank you very much

**Comment by AlyoshaVasilieva** [comment]
As of [v0.5.0](https://github.com/AlyoshaVasilieva/luminous-ttv/releases/tag/v0.5.0), yes, unless I messed something up.

**Comment by thinkpad4** [comment]
Sweet, thanks
